export const IMG_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const restaurantList = [
  {
    type: "F",
    id: "533773",
    name: "Third Wave Coffee",
    uuid: "19dff2cd-d21d-4cac-9c26-4580e0c61346",
    city: "1",
    area: "Ashok Nagar",
    totalRatingsString: "100+ ratings",
    cloudinaryImageId: "0dca660dbdf2e04f9b861c4426ffd41e",
    cuisines: ["Beverages", "Bakery", "Continental"],
    tags: [],
    costForTwo: 40000,
    costForTwoString: "₹400 FOR TWO",
    deliveryTime: 17,
    minDeliveryTime: 17,
    maxDeliveryTime: 17,
    slaString: "17 MINS",
    lastMileTravel: 0.5,
    slugs: {
      restaurant: "third-wave-coffee-central-bangalore-central-bangalore",
      city: "bangalore",
    },
    cityState: "1",
    address:
      "hird Wave Coffee, Corporation No.13, Old No.4/1, Ground Floor, Lavelle Road Junction, Walton Road, Bangalore, Shanthinagara , B.B.M.P East, Karnataka-560001",
    locality: "Lavelle Road",
    parentId: 274773,
    unserviceable: false,
    veg: false,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    ribbon: [
      {
        type: "PROMOTED",
      },
    ],
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 3200,
          message: "",
        },
        {
          name: "time",
          fee: 0,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 3200,
      message: "",
      title: "Delivery Charge",
      amount: "3200",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "cid=6846528~p=19~eid=00000188-66cf-008f-7f6b-976f0070133b",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "0.5 kms",
    hasSurge: false,
    aggregatedDiscountInfoV3: {
      header: "30% OFF",
      subHeader: "UPTO ₹75",
      discountTag: "",
      headerTypeV2: 0,
    },
    sla: {
      restaurantId: "533773",
      deliveryTime: 17,
      minDeliveryTime: 17,
      maxDeliveryTime: 17,
      lastMileTravel: 0.5,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: true,
    avgRating: "4.3",
    totalRatings: 100,
    new: false,
  },
  {
    type: "F",
    id: "3241",
    name: "Meghana Foods",
    uuid: "93695df0-56e1-417e-b9a8-32084ebaadaf",
    city: "1",
    area: "Ashok Nagar",
    totalRatingsString: "10000+ ratings",
    cloudinaryImageId: "e0vvulfbahjxjz6k4uwi",
    cuisines: [
      "Biryani",
      "Andhra",
      "South Indian",
      "North Indian",
      "Chinese",
      "Seafood",
    ],
    tags: [],
    costForTwo: 50000,
    costForTwoString: "₹500 FOR TWO",
    deliveryTime: 20,
    minDeliveryTime: 20,
    maxDeliveryTime: 20,
    slaString: "20 MINS",
    lastMileTravel: 2.4000000953674316,
    slugs: {
      restaurant: "meghana-foods-central-bangalore",
      city: "bangalore",
    },
    cityState: "1",
    address:
      "57/1, 1st Floor, Jayalaxmi Chambers, Next to Old Galaxy Theatre,Residency Road, Bangalore",
    locality: "Residency Road",
    parentId: 635,
    unserviceable: false,
    veg: false,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 3200,
          message: "",
        },
        {
          name: "time",
          fee: 0,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 3200,
      message: "",
      title: "Delivery Charge",
      amount: "3200",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 0,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "2.4 kms",
    hasSurge: false,
    sla: {
      restaurantId: "3241",
      deliveryTime: 20,
      minDeliveryTime: 20,
      maxDeliveryTime: 20,
      lastMileTravel: 2.4000000953674316,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "NOT_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "4.5",
    totalRatings: 10000,
    new: false,
  },
  {
    type: "F",
    id: "121603",
    name: "Kannur Food Point",
    uuid: "51983905-e698-4e31-b0d7-e376eca56320",
    city: "1",
    area: "Tavarekere",
    totalRatingsString: "10000+ ratings",
    cloudinaryImageId: "bmwn4n4bn6n1tcpc8x2h",
    cuisines: ["Kerala", "Chinese"],
    tags: [],
    costForTwo: 30000,
    costForTwoString: "₹300 FOR TWO",
    deliveryTime: 28,
    minDeliveryTime: 28,
    maxDeliveryTime: 28,
    slaString: "28 MINS",
    lastMileTravel: 6.699999809265137,
    slugs: {
      restaurant: "kannur-food-point-btm",
      city: "bangalore",
    },
    cityState: "1",
    address:
      "6/21,9TH CROSS ,1ST MAIN, VENKATESHWARA LAYOUT,SG PALYA, BENGALURU, - 560093",
    locality: "SG Palya",
    parentId: 20974,
    unserviceable: false,
    veg: false,
    select: false,
    favorite: false,
    tradeCampaignHeaders: [],
    chain: [],
    feeDetails: {
      fees: [
        {
          name: "distance",
          fee: 5600,
          message: "",
        },
        {
          name: "time",
          fee: 0,
          message: "",
        },
        {
          name: "special",
          fee: 0,
          message: "",
        },
      ],
      totalFees: 5600,
      message: "",
      title: "Delivery Charge",
      amount: "5600",
      icon: "",
    },
    availability: {
      opened: true,
      nextOpenMessage: "",
      nextCloseMessage: "",
    },
    longDistanceEnabled: 1,
    rainMode: "NONE",
    thirdPartyAddress: false,
    thirdPartyVendor: "",
    adTrackingID: "",
    badges: {
      imageBased: [],
      textBased: [],
      textExtendedBadges: [],
    },
    lastMileTravelString: "6.6 kms",
    hasSurge: false,
    sla: {
      restaurantId: "121603",
      deliveryTime: 28,
      minDeliveryTime: 28,
      maxDeliveryTime: 28,
      lastMileTravel: 6.699999809265137,
      lastMileDistance: 0,
      serviceability: "SERVICEABLE",
      rainMode: "NONE",
      longDistance: "IT_IS_LONG_DISTANCE",
      preferentialService: false,
      iconType: "EMPTY",
    },
    promoted: false,
    avgRating: "3.9",
    totalRatings: 10000,
    new: false,
  },
];
